=== TFOMS/IC_SMEV3/smev3-tfoms-information-system/core/xml-artifacts/104/omsEXPQ.xsd
<?xml version="1.0" encoding="windows-1251"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="types.xsd"/>
    <xs:element name="EXPQ_OB">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ZGLV">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="VERSION" type="string5" minOccurs="1"/>
                            <xs:element name="DATA" type="DateShort" minOccurs="1"/>
                            <xs:element name="FILENAME" type="string26" minOccurs="1"/>
                            <xs:element name="FIRSTNAME" type="string26" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="SVD">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CODE" type="positive-integer-8" minOccurs="1"/>
                            <xs:element name="YEAR" type="positive-integer-4" minOccurs="1"/>
                            <xs:element name="MONTH" type="positive-integer-2" minOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="RECORDS">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element minOccurs="0" maxOccurs="unbounded" name="REC">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="TYPE" type="positive-integer-1" minOccurs="1"/>
                                        <xs:element name="TYPE_CARE" type="positive-integer-1" minOccurs="1"/>
                                        <xs:element name="AGE" type="positive-integer-1" minOccurs="1"/>
                                        <xs:element name="DS" type="string10" minOccurs="1"/>
                                        <xs:element name="IND" type="string10" minOccurs="1"/>
                                        <xs:element name="CNT" type="positive-integer-9" minOccurs="1"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== TFOMS/IC_SMEV3/smev3-tfoms-information-system/core/xml-artifacts/104/omsEXPQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<EXPQ_OB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="omsEXPQ.xsd">
  <ZGLV>
    <VERSION>VERSION</VERSION>
    <DATA>2001-01-01</DATA>
    <FILENAME>FILENAME</FILENAME>
    <FIRSTNAME>FIRSTNAME</FIRSTNAME>
  </ZGLV>
  <SVD>
    <CODE>0</CODE>
    <YEAR>0</YEAR>
    <MONTH>0</MONTH>
  </SVD>
  <RECORDS>
    <REC>
      <TYPE>0</TYPE>
      <TYPE_CARE>0</TYPE_CARE>
      <AGE>0</AGE>
      <DS>DS</DS>
      <IND>IND</IND>
      <CNT>0</CNT>
    </REC>
  </RECORDS>
</EXPQ_OB>
